export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AllBlogsLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="flex flex-col min-h-screen">
          

          {/* Page Content */}
          <main className="flex-grow">
            {children}
          </main>

          
        </div>
      </body>
    </html>
  );
}
